image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      go install github.com/golang/protobuf/protoc-gen-go@latest
      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      go get ./...
  - name: workspace
    command: |
      okteto context use https://cloud.okteto.com
      okteto context update-kubeconfig
vscode:
  extensions:
    - zxh404.vscode-proto3
    - ms-kubernetes-tools.vscode-kubernetes-tools
