// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: protos/blocker.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlockerClient is the client API for Blocker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockerClient interface {
	ToggleBlocker(ctx context.Context, in *ToggleBlockerRequest, opts ...grpc.CallOption) (*ToggleBlockerResponse, error)
}

type blockerClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockerClient(cc grpc.ClientConnInterface) BlockerClient {
	return &blockerClient{cc}
}

func (c *blockerClient) ToggleBlocker(ctx context.Context, in *ToggleBlockerRequest, opts ...grpc.CallOption) (*ToggleBlockerResponse, error) {
	out := new(ToggleBlockerResponse)
	err := c.cc.Invoke(ctx, "/Blocker/ToggleBlocker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockerServer is the server API for Blocker service.
// All implementations must embed UnimplementedBlockerServer
// for forward compatibility
type BlockerServer interface {
	ToggleBlocker(context.Context, *ToggleBlockerRequest) (*ToggleBlockerResponse, error)
	mustEmbedUnimplementedBlockerServer()
}

// UnimplementedBlockerServer must be embedded to have forward compatible implementations.
type UnimplementedBlockerServer struct {
}

func (UnimplementedBlockerServer) ToggleBlocker(context.Context, *ToggleBlockerRequest) (*ToggleBlockerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleBlocker not implemented")
}
func (UnimplementedBlockerServer) mustEmbedUnimplementedBlockerServer() {}

// UnsafeBlockerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockerServer will
// result in compilation errors.
type UnsafeBlockerServer interface {
	mustEmbedUnimplementedBlockerServer()
}

func RegisterBlockerServer(s grpc.ServiceRegistrar, srv BlockerServer) {
	s.RegisterService(&Blocker_ServiceDesc, srv)
}

func _Blocker_ToggleBlocker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleBlockerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockerServer).ToggleBlocker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Blocker/ToggleBlocker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockerServer).ToggleBlocker(ctx, req.(*ToggleBlockerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Blocker_ServiceDesc is the grpc.ServiceDesc for Blocker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blocker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Blocker",
	HandlerType: (*BlockerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToggleBlocker",
			Handler:    _Blocker_ToggleBlocker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/blocker.proto",
}
