name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang
    steps:
      - uses: actions/checkout@v2
      - name: install gotestsum
        run: go get -u gotest.tools/gotestsum
      - name: test
        run: gotestsum
